### ISSUE TITLE
Fehlermeldung "Sketch is too big"

### ISSUE THREAD

**Issue by Napizaki** [AWSW-de/WordClock-16x16-LED-matrix#10]
Hallo,

wenn ich, wie in der Videoanleitung beschrieben, die V3.80 für einen WEMOS D1 MINI ESP32 kompilieren möchte, bekomme ich folgende Fehlermeldung:

![image](https://github.com/AWSW-de/WordClock-16x16-LED-matrix/assets/126354867/f49d5e84-dc63-4357-99e1-a68380f153c1)

Alle Libraries sind die derzeit aktuellen.

**Comment by AWSW-de** [comment]
Hallo,
ich habe das gerade mit komplett neuer Installation probiert mit dem Skript (https://github.com/AWSW-de/AWSW-WordClock-Windows-setup-script) installiert und dann nur noch die ESP32 Boards installiert:

![grafik](https://github.com/AWSW-de/WordClock-16x16-LED-matrix/assets/34800740/d86a92c5-1ba9-43a3-b6bf-eb3efb04fe48)

Damit konnte ich das Verhalten nachvollziehen. Das Problem scheint die neue Version 3.0.0 der ESP32 Boards von Expressive zu sein. Bitte im Bordverwalter die ESP32 Board Version von 3.0.0 wieder auf 2.0.17 stellen und somit downgraden:

![grafik](https://github.com/AWSW-de/WordClock-16x16-LED-matrix/assets/34800740/d1424175-4300-48d2-853f-939ec95fc137)

![grafik](https://github.com/AWSW-de/WordClock-16x16-LED-matrix/assets/34800740/50358187-a5a7-4efe-acd8-d5e5edeebb58)

Denke, die ESP32 V3.0.0 hat noch einen Bug. Daher bitte die vorherige Version verwenden und dann kopiliert der Code wieder:

![grafik](https://github.com/AWSW-de/WordClock-16x16-LED-matrix/assets/34800740/01e40bc5-e928-419e-b516-c4ec63593788)

Viel Spaß mit der WordClock. =)

Viele Grüße
AWSW

**Comment by AWSW-de** [comment]
Habe die FAQs für die 16x16 und 16x8 WordClocks erweitert

**Comment by Napizaki** [comment]
Perfekt, hat funktioniert. Danke für die schnelle Hilfe!!!

**Comment by AWSW-de** [comment]
Alles klar, danke fürs Feedback. Ich schließe das Ticket und hoffe, der Bug wird bald behoben.

**Comment by AWSW-de** [comment]
Moin, na wenigstens liegt es nicht an meinem Code, welcher in verschiedenen Projekten nun das gleiche Verhalten zeigt.
Wurde bereits gemeldet https://github.com/espressif/arduino-esp32/issues/9741 und mal sehen wann es behoben wird...
