### ISSUE TITLE
Compilation  Error

### ISSUE THREAD

**Issue by Corbin1747** [AWSW-de/WordClock-16x16-LED-matrix#12]
Hey I wanted to update the clock from 3.8 to 3.9. I compiled your code and there is an error on like 138
Compilation error: 'strip' was not declared in this scope

**Comment by Corbin1747** [comment]
Never mind. User error. When I copied the settings file I typed the name out and forgot the ".h"

**Comment by AWSW-de** [comment]
Hi, 
yes that usually is shown when the settings.h file can’t be found.
Kind regards and enjoy your WordClock =)
