### ISSUE TITLE
Compiles to 101% of esp32 wroom

### ISSUE THREAD

**Issue by amrak44** [AWSW-de/WordClock-16x16-LED-matrix#15]
i was able to slim this down, but no matter what micro controller i use, it results in a boot loop

4:20:33.071 -> E (25) boot: load partition table error!
04:20:33.071 -> E (25) flash_parts: partition 0 invalid magic number 0xcccf
04:20:33.071 -> E (25) boot: Failed to verify partition table
04:20:33.110 -> E (25) boot: load partition table error!

I have tried multiple of each of these types esp32S3; esp32C3; esp32; wemos d1;

used microsoft development VM for fresh environment, downloaded sources via powershell script that was recommended.  At a standstill, i can flash say wled onto the same chip and it will run just fine.

**Comment by AWSW-de** [comment]
Hello,
no code changes needed at all.. You simply not use the recommended libraries as noted in the FAQ. Downgrade them to the named versions or simply use this script to setup everything for you automatically: https://github.com/AWSW-de/AWSW-WordClock-Windows-setup-script

The Arduino IDE will try to update the libraries when you did not use the script and then the new libraries will be installed again and then it does not fit.

The named ESP32 should be used so no C3 or S3 model please. 

Compiled the code this week several times and it will work right with the correct board manager and components libraries.

Hope to help =)
