### ISSUE TITLE
restarting

### ISSUE THREAD

**Issue by degerang** [AWSW-de/WordClock-16x16-LED-matrix#6]
hello 
hi the AZ delivery es32 d1 mini keep restarting 

![error](https://github.com/AWSW-de/WordClock-16x16-LED-matrix/assets/26428103/6cdd174e-0155-4d27-8e6b-626c31967e5f)
![error](https://github.com/AWSW-de/WordClock-16x16-LED-matrix/assets/26428103/a0feadc9-d8f8-4d3e-902b-900a3658ef81)

**Comment by AWSW-de** [comment]
Hello,
looks like a power issue… Try to use a shorter or better USB cable and make sure to use the recommended 5V/3A power supply. 

Hope to help and kind regards =)
