### ISSUE TITLE
Fehlermeldung beim Installieren

### ISSUE THREAD

**Issue by Plampi20** [AWSW-de/WordClock-16x16-LED-matrix#9]
Hallo was kann ich machen, das diese Meldung nicht mehr kommt, und ich alles Installieren kann um die Uhr zu Starten.
Fehlermeldung ist folgende:
C:\Users\19pla\Downloads\AWSW-WordClock-Code\WordClock-16x16-LED-matrix-main\Code\Code.ino:47:10: fatal error: Adafruit_NeoPixel.h: No such file or directory
 #include <Adafruit_NeoPixel.h>     // Used to drive the NeoPixel LEDs
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: Adafruit_NeoPixel.h: No such file or directory

Ich habe alle Dateien in den Libarie im Arduino PLC IDE ordner abgelegt.

![Screenshot 2024-04-28 200314](https://github.com/AWSW-de/WordClock-16x16-LED-matrix/assets/135654655/d6534111-c070-4310-b9a1-9ff178efadea)

**Comment by AWSW-de** [comment]
Hi, 
die Libraries, die oben in der Code.ino als Links angegeben sind, scheinen zu fehlen. Zur Installation siehe: https://youtu.be/BrVKY1sfZgI?si=E-b_kccjOUfWDsNv 
oder dieses Skript zur automatischen Installation nutzen: https://github.com/AWSW-de/AWSW-WordClock-Windows-setup-script

Viele Grüße 🖖

**Comment by Plampi20** [comment]
Ich habe das Skript zur automatischen Installation benutzt.

**Comment by AWSW-de** [comment]
In dem Fall liegen die Libraries schon im richtigen Ordner und müssen nicht in einen anderen Ordner gelegt werden. Bitte das Video noch mal schauen und dann ggf. noch mal das Skript ausführen. Einzig, wie im Video gezeigt. müssen die ESP32 Boardtreiber noch installiert werden. Dann funktioniert es. Viel Erfolg.

**Comment by AWSW-de** [comment]
Gerade noch mal aktuell geprüft und kappt 1a: 

![Screenshot (1)](https://github.com/AWSW-de/WordClock-16x16-LED-matrix/assets/34800740/290de52e-de47-44d1-af58-91da1ec18a90)
